[package]
name = "project-name"
version = "0.1.0"
authors = ["William Findlay <william@williamfindlay.com>"]
edition = "2018"

[dependencies]
libbpf-rs = "0.11.0"
anyhow = "1.0.38"
pod = "0.5.0"

[build-dependencies]
bindgen = "0.56.0"
glob = "0.3.0"
libbpf-cargo = "0.7.1"
uname = "0.1.1"
